In [90]:
import random

import numpy as np

1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [91]:
data = np.genfromtxt(' https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype=str)
data.shape  # (150, 5)


(150, 5)

In [92]:
data[:][:data.shape[1]]  # float, float, float, float, string - target

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa']], dtype='<U15')

In [93]:
target = data[:, -1]
dataset = np.delete(data, -1, axis=1)

print("Dataset without target:")
print(dataset)
print("Target:")
print(target)

Dataset without target:
[['5.1' '3.5' '1.4' '0.2']
 ['4.9' '3.0' '1.4' '0.2']
 ['4.7' '3.2' '1.3' '0.2']
 ['4.6' '3.1' '1.5' '0.2']
 ['5.0' '3.6' '1.4' '0.2']
 ['5.4' '3.9' '1.7' '0.4']
 ['4.6' '3.4' '1.4' '0.3']
 ['5.0' '3.4' '1.5' '0.2']
 ['4.4' '2.9' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.4' '3.7' '1.5' '0.2']
 ['4.8' '3.4' '1.6' '0.2']
 ['4.8' '3.0' '1.4' '0.1']
 ['4.3' '3.0' '1.1' '0.1']
 ['5.8' '4.0' '1.2' '0.2']
 ['5.7' '4.4' '1.5' '0.4']
 ['5.4' '3.9' '1.3' '0.4']
 ['5.1' '3.5' '1.4' '0.3']
 ['5.7' '3.8' '1.7' '0.3']
 ['5.1' '3.8' '1.5' '0.3']
 ['5.4' '3.4' '1.7' '0.2']
 ['5.1' '3.7' '1.5' '0.4']
 ['4.6' '3.6' '1.0' '0.2']
 ['5.1' '3.3' '1.7' '0.5']
 ['4.8' '3.4' '1.9' '0.2']
 ['5.0' '3.0' '1.6' '0.2']
 ['5.0' '3.4' '1.6' '0.4']
 ['5.2' '3.5' '1.5' '0.2']
 ['5.2' '3.4' '1.4' '0.2']
 ['4.7' '3.2' '1.6' '0.2']
 ['4.8' '3.1' '1.6' '0.2']
 ['5.4' '3.4' '1.5' '0.4']
 ['5.2' '4.1' '1.5' '0.1']
 ['5.5' '4.2' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.0' '3.2' '1.2' '0.2']
 ['5

2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [94]:
dataset = dataset.astype(float)
if len(dataset.shape) == 2:
    print("Dataset is 2D")
else:
    data_2d = np.atleast_2d(dataset)
    print("Dataset is changed to 2D")

Dataset is 2D


3. Порахувати mean, median, standard deviation для 1-ї колонки

In [95]:
first_col = dataset[:, 0]
mean = np.mean(first_col)
median = np.median(first_col)
standard_deviation = np.std(first_col)
print(f"Mean: {mean}, Median: {median}, Standard deviation: {standard_deviation}")


Mean: 5.843333333333334, Median: 5.8, Standard deviation: 0.8253012917851409


4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [96]:
set_len = 20
random_set = set()
first_col_nan = first_col
while len(random_set) < set_len:
    random_set.add(random.randint(0, len(first_col) - 1))
for i in random_set:
    first_col_nan[i] = np.nan
print(first_col_nan)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 nan 4.8 nan 4.3 5.8 nan 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  nan 5.2 nan 4.7 4.8 5.4 nan 5.5 4.9 5.
 5.5 4.9 4.4 5.1 nan 4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 nan nan 6.3 4.9 nan 5.2 nan 5.9 6.  6.1 nan 6.7 5.6 5.8 6.2 5.6 nan nan
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  nan 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 nan 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 nan 7.9 6.4 nan 6.1 7.7 nan 6.4 nan 6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


5. Знайти позиції вставлених значень np.nan в 1-й колонці

In [97]:
nan_positions = np.where(np.isnan(first_col_nan))[0]
print(f"Nan positions: {nan_positions}")

Nan positions: [ 10  12  15  26  28  32  40  54  55  58  60  64  70  71  84 108 130 133
 136 138]


6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)


In [98]:
filtered_dataset1 = dataset[(dataset[:,2] > 1.5) & (dataset[:, 0] < 5.0)].copy()
print(filtered_dataset1)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [99]:
condition = (dataset[:, 2] > 1.5) & (dataset[:, 0] < 5.0)
filtered_dataset2 = dataset[np.where(condition)].copy()
print(filtered_dataset2)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


7. Замінити всі значення np.nan на 0


In [100]:
dataset_wo_nan = np.nan_to_num(dataset, True, 0)
print(dataset_wo_nan)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [0.  3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [0.  3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [0.  4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [0.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [0.  3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [0.  4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [0.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [101]:
unique_values, counts = np.unique(dataset, return_counts=True)
for value, count in zip(unique_values, counts):
    print(f"Value: {value}, Count: {count}")
print(f"Total count: {len(unique_values)}")

Value: 0.1, Count: 6
Value: 0.2, Count: 28
Value: 0.3, Count: 7
Value: 0.4, Count: 7
Value: 0.5, Count: 1
Value: 0.6, Count: 1
Value: 1.0, Count: 8
Value: 1.1, Count: 4
Value: 1.2, Count: 7
Value: 1.3, Count: 20
Value: 1.4, Count: 20
Value: 1.5, Count: 26
Value: 1.6, Count: 11
Value: 1.7, Count: 6
Value: 1.8, Count: 12
Value: 1.9, Count: 7
Value: 2.0, Count: 7
Value: 2.1, Count: 6
Value: 2.2, Count: 6
Value: 2.3, Count: 12
Value: 2.4, Count: 6
Value: 2.5, Count: 11
Value: 2.6, Count: 5
Value: 2.7, Count: 9
Value: 2.8, Count: 14
Value: 2.9, Count: 10
Value: 3.0, Count: 27
Value: 3.1, Count: 12
Value: 3.2, Count: 13
Value: 3.3, Count: 8
Value: 3.4, Count: 12
Value: 3.5, Count: 8
Value: 3.6, Count: 4
Value: 3.7, Count: 4
Value: 3.8, Count: 7
Value: 3.9, Count: 5
Value: 4.0, Count: 6
Value: 4.1, Count: 4
Value: 4.2, Count: 5
Value: 4.3, Count: 3
Value: 4.4, Count: 8
Value: 4.5, Count: 9
Value: 4.6, Count: 7
Value: 4.7, Count: 7
Value: 4.8, Count: 8
Value: 4.9, Count: 11
Value: 5.0, Count: 

9. Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [102]:
first_dataset1, second_dataset1 = np.vsplit( dataset_wo_nan, 2)
print(f"First dataset: \n{first_dataset1}.\nLength: {len(first_dataset1)}\n")
print(f"Second dataset: \n{second_dataset1}.\nLength: {len(second_dataset1)}")

First dataset: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [0.  3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [0.  3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [0.  4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [0.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [0.  3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [0.  4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [0.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1

In [103]:
first_dataset2, second_dataset2 = dataset_wo_nan[:int(dataset_wo_nan.shape[0]/2), :], dataset_wo_nan[int(dataset_wo_nan.shape[0]/2):, :]
print(f"First dataset: \n{first_dataset2}.\nLength: {len(first_dataset2)}\n")
print(f"Second dataset: \n{second_dataset2}.\nLength: {len(second_dataset2)}")

First dataset: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [0.  3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [0.  3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [0.  4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [0.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [0.  3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [0.  4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [0.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1

In [104]:
print(f"Are they the same?\n{all([np.array_equal(first_dataset1, first_dataset2), np.array_equal(second_dataset1, second_dataset2)])}")

Are they the same?
True


10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [105]:
ascending_indices = first_dataset1[:, 0].argsort()
descending_indices = second_dataset1[:, 0].argsort()[::-1]

print("Sorted Indices (Ascending):\n", first_dataset1[ascending_indices])
print("Sorted Elements (Descending):\n", second_dataset1[descending_indices])

Sorted Indices (Ascending):
 [[0.  3.  1.4 0.1]
 [0.  4.4 1.5 0.4]
 [0.  3.7 1.5 0.2]
 [0.  3.4 1.4 0.2]
 [0.  3.4 1.6 0.4]
 [0.  2.8 4.5 1.3]
 [0.  3.5 1.3 0.3]
 [0.  4.1 1.5 0.1]
 [0.  2.8 4.6 1.5]
 [0.  2.9 4.6 1.3]
 [0.  2.  3.5 1. ]
 [0.  2.9 3.6 1.3]
 [0.  2.8 4.  1.3]
 [0.  3.2 4.8 1.8]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [4.6 3.1 1.5 0.2]
 [4.7 3.2 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.6 0.6]
 [5.  3.6 1.4 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.2 1.2 0.2]
 [5.  3.4 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [5.1 3.5 1.4 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 3.3 1.7 0.5]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.8 1.9 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [

11. Зібрати обидва массиви в одне ціле

In [106]:
conc_dataset = np.concatenate([first_dataset1, second_dataset1], axis=0)
print(f"Concatenated dataset: {conc_dataset}")
print(f"Is it correctly concatenated?\n{np.array_equal(dataset_wo_nan, conc_dataset)}")

Concatenated dataset: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [0.  3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [0.  3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [0.  4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [0.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [0.  3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [0.  4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [0.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2

12. Знайти найбільш часто повторюване значення в массиві

In [107]:
unique_values, counts = np.unique(conc_dataset.flatten(), return_counts=True)
print(f"The most frequently repeated value: {unique_values[np.argmax(counts)]}")

The most frequently repeated value: 0.2


13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [108]:
def multiply_divide(column):
    mean = np.mean(column)
    column = [float(el * 2) if el < mean else float(el / 4) for i, el in enumerate(column) ]
    return column

print(multiply_divide(conc_dataset[:, 2]))

[2.8, 2.8, 2.6, 3.0, 2.8, 3.4, 2.8, 3.0, 2.8, 3.0, 3.0, 3.2, 2.8, 2.2, 2.4, 3.0, 2.6, 2.8, 3.4, 3.0, 3.4, 3.0, 2.0, 3.4, 3.8, 3.2, 3.2, 3.0, 2.8, 3.2, 3.2, 3.0, 3.0, 2.8, 3.0, 2.4, 2.6, 3.0, 2.6, 3.0, 2.6, 2.6, 2.6, 3.2, 3.8, 2.8, 3.2, 2.8, 3.0, 2.8, 1.175, 1.125, 1.225, 1.0, 1.15, 1.125, 1.175, 6.6, 1.15, 0.975, 7.0, 1.05, 1.0, 1.175, 7.2, 1.1, 1.125, 1.025, 1.125, 0.975, 1.2, 1.0, 1.225, 1.175, 1.075, 1.1, 1.2, 1.25, 1.125, 7.0, 0.95, 7.4, 0.975, 1.275, 1.125, 1.125, 1.175, 1.1, 1.025, 1.0, 1.1, 1.15, 1.0, 6.6, 1.05, 1.05, 1.05, 1.075, 6.0, 1.025, 1.5, 1.275, 1.475, 1.4, 1.45, 1.65, 1.125, 1.575, 1.45, 1.525, 1.275, 1.325, 1.375, 1.25, 1.275, 1.325, 1.375, 1.675, 1.725, 1.25, 1.425, 1.225, 1.675, 1.225, 1.425, 1.5, 1.2, 1.225, 1.4, 1.45, 1.525, 1.6, 1.4, 1.275, 1.4, 1.525, 1.4, 1.375, 1.2, 1.35, 1.4, 1.275, 1.275, 1.475, 1.425, 1.3, 1.25, 1.3, 1.35, 1.275]
